#!/usr/bin/env bash

window_name=$(basename "$1")
session_name=$(tmux display-message -p "#S")
clean_name=$(echo $window_name | tr "./" "__")
target="$session_name:$clean_name"

if ! tmux has-session -t $target 2>/dev/null; then
  tmux neww -dn $clean_name
fi

shift

if [[ $# -gt 0 ]]; then
  tmux send-keys -t $target "$*" C-m
  shift
fi

tmux select-window -t "$target"
