unbind r
bind r source-file ~/.tmux.conf # reload tmux config

set -g default-terminal "tmux-256color" # set terminal to 256 colors
set -ag terminal-overrides ",xterm-256color:RGB" # set terminal to rgb colors

set-option -sg escape-time 10 # set escape time to 10ms
set-option -g focus-events on # enable focus events

# set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on # enable mouse support...for now

# set window numbers to start at 1
set -g base-index 1
set -g pane-base-index 1

# tmux window nav
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top # set status bar to top

# theme stuff
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_window_text " #W"

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.dotfiles/scripts/tmux-sessionizer"

# project specific setups
bind-key -r S run-shell "~/.dotfiles/scripts/tmux-nerd.sh"
bind-key -r K run-shell "~/.dotfiles/scripts/tmux-cw2.sh"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux'

set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

# initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
